"""add_practice_sessions

Revision ID: 1035e88d8fa3
Revises: 16fb6640ab32
Create Date: 2025-09-08 16:26:09.183865

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as pg
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1035e88d8fa3"
down_revision: Union[str, Sequence[str], None] = "16fb6640ab32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column(
            "session_type",
            pg.ENUM(name="sessiontype", create_type=False),
            nullable=False,
            create_type=False,
        ),
        sa.Column("tempo", sa.Integer(), nullable=True),
        sa.Column("difficulty_level", sa.Integer(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("instrument", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["common.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="practice",
    )
    op.create_index(
        op.f("ix_practice_sessions_id"),
        "sessions",
        ["id"],
        unique=False,
        schema="practice",
    )
    op.create_table(
        "sessions_goals",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("goal_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["practice.goals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["practice.sessions.id"],
        ),
        sa.PrimaryKeyConstraint("session_id", "goal_id"),
        schema="practice",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sessions_goals", schema="practice")
    op.drop_index(
        op.f("ix_practice_sessions_id"), table_name="sessions", schema="practice"
    )
    op.drop_table("sessions", schema="practice")
    # ### end Alembic commands ###
