"""add_practice_goals

Revision ID: 16fb6640ab32
Revises: 6f59c7e1e5ac
Create Date: 2025-09-08 11:18:22.855373

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16fb6640ab32"
down_revision: Union[str, Sequence[str], None] = "6f59c7e1e5ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the practice schema if it doesn't exist
    op.execute("CREATE SCHEMA IF NOT EXISTS practice")

    op.create_table(
        "goals",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("goal_type", sa.Enum("PRACTICE", name="goaltype"), nullable=False),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "COMPLETED", "PAUSED", "CANCELLED", name="goalstatus"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("target_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("target", sa.Integer(), nullable=False),
        sa.Column(
            "target_type",
            sa.Enum(
                "MINUTES",
                "HOURS",
                "DAYS",
                "WEEKS",
                "MONTHS",
                "SESSIONS",
                name="practicetargettype",
            ),
            nullable=False,
        ),
        sa.Column(
            "target_interval",
            sa.Enum("DAY", "WEEK", "MONTH", "YEAR", name="practiceinterval"),
            nullable=False,
        ),
        sa.Column(
            "instrument", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["common.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="practice",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("goals", schema="practice")
    op.execute("DROP SCHEMA IF EXISTS practice")
    # ### end Alembic commands ###
