"""session_add_description

Revision ID: 516e1ca20cb5
Revises: 972ef5f351a8
Create Date: 2025-09-16 07:55:28.924849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '516e1ca20cb5'
down_revision: Union[str, Sequence[str], None] = '972ef5f351a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='practice')
    op.add_column('sessions', sa.Column('stopped_at', sa.DateTime(), nullable=True), schema='practice')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'stopped_at', schema='practice')
    op.drop_column('sessions', 'description', schema='practice')
    # ### end Alembic commands ###
