"""Initial migration with schema creation

Revision ID: 6f59c7e1e5ac
Revises:
Create Date: 2025-09-03 16:41:41.539077

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f59c7e1e5ac"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the common schema if it doesn't exist
    op.execute("CREATE SCHEMA IF NOT EXISTS common")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "keycloak_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("timezone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="common",
    )
    op.create_index(
        op.f("ix_common_users_email"), "users", ["email"], unique=False, schema="common"
    )
    op.create_index(
        op.f("ix_common_users_keycloak_user_id"),
        "users",
        ["keycloak_user_id"],
        unique=True,
        schema="common",
    )
    op.create_index(
        op.f("ix_common_users_username"),
        "users",
        ["username"],
        unique=False,
        schema="common",
    )
    op.create_table(
        "user_settings",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "default_session_type",
            sa.Enum(
                "EXERCISE",
                "FREE_PLAY",
                "SONG",
                "STRUCTURED",
                "TECHNIQUE",
                name="sessiontype",
            ),
            nullable=False,
        ),
        sa.Column("preferred_tempo_range_min", sa.Integer(), nullable=True),
        sa.Column("preferred_tempo_range_max", sa.Integer(), nullable=True),
        sa.Column("default_difficulty_level", sa.Integer(), nullable=True),
        sa.Column("daily_practice_goal_minutes", sa.Integer(), nullable=False),
        sa.Column("weekly_practice_goal_sessions", sa.Integer(), nullable=False),
        sa.Column(
            "theme", sa.Enum("LIGHT", "DARK", "SYSTEM", name="theme"), nullable=False
        ),
        sa.Column("profile_public", sa.Boolean(), nullable=False),
        sa.Column("share_practice_stats", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["common.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="common",
    )
    op.create_index(
        op.f("ix_common_user_settings_user_id"),
        "user_settings",
        ["user_id"],
        unique=True,
        schema="common",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_common_user_settings_user_id"),
        table_name="user_settings",
        schema="common",
    )
    op.drop_table("user_settings", schema="common")
    op.drop_index(op.f("ix_common_users_username"), table_name="users", schema="common")
    op.drop_index(
        op.f("ix_common_users_keycloak_user_id"), table_name="users", schema="common"
    )
    op.drop_index(op.f("ix_common_users_email"), table_name="users", schema="common")
    op.drop_table("users", schema="common")

    # Drop the common schema (optional - comment out if you want to keep the schema)
    # op.execute("DROP SCHEMA IF EXISTS common")
    # ### end Alembic commands ###
