"""session_add_duration

Revision ID: 972ef5f351a8
Revises: 1035e88d8fa3
Create Date: 2025-09-15 09:26:43.282713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '972ef5f351a8'
down_revision: Union[str, Sequence[str], None] = '1035e88d8fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('duration', sa.Integer(), nullable=True), schema='practice')
    op.drop_column('sessions', 'ended_at', schema='practice')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='practice')
    op.drop_column('sessions', 'duration', schema='practice')
    # ### end Alembic commands ###
